### ISSUE TITLE
Interactivite nouveaux messages

### ISSUE THREAD

**Issue by kiwec** [kiwec/TopicLive#14]
JVC a retiré le support pour les userscript, il faut réécrire ces fonctions.
- [x] Citation
- [x] Citations dans le message
- [x] Blacklist
- [x] DDB
- [x] Suppression
- [x] Edition
- [ ] Restauration
- [ ] Kick

**Comment by vitoo** [comment]
Salut,

Ca serait chouette le support des MP JVC en mode live
On dirait que ça marche avec quelques bugs

**Comment by kiwec** [comment]
Ce script supporte les MP, mais comme pour les messages certaines fonctionnalités causent des bugs.
Vu que les MP n'ont pas d'ID, je suis obligé d'analyser le contenu du message -> et pour les citations, spoilers, etc, le contenu est modifié par les scripts de JVC, ce qui fait bug l'affichage vu que je ne gère plus ca.

**Comment by vitoo** [comment]
Salut,

Actuellement ça post 2 messages chez moi avec les MP

**Comment by kiwec** [comment]
Je ne suis pas modérateur donc je ne peux pas tester les boutons de modération. Le reste fonctionne sur la branche dev.
