### ISSUE TITLE
Ne fonctionne plus ?

### ISSUE THREAD

**Issue by awsms** [kiwec/TopicLive#19]
L'userscript ne fonctionne plus depuis quelques heures, pourtant 
>[TopicLive] Initialisation

et

>[TopicLive] TopicLive actif sur cette page.

apparaissent bien dans la console

**Comment by kiwec** [comment]
Fonctionne encore chez moi :/

Tu as un topic sur lequel ça ne fonctionne pas en particulier ? Essaie de vider ton cache ou d'essayer sur un autre navigateur, pour voir ?

**Comment by awsms** [comment]
Effectivement, cela refonctionne.
Le bug n'a duré que quelques heures (et était présent sur tous les navigateurs que j'ai testé)
